version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    volumes:
      - db_volume:/var/lib/mysql
      - ./env/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports: 
      - "3306:3306"
    restart: always
    env_file: .env

  wordpress:
    depends_on:
      - mysql
    build: .
    container_name: wordpress-container
    volumes:
      - ../themes/sample:/var/www/html/wp-content/themes/sample
      #- ../themes/hoge:/var/www/html/wp-content/themes/hoge # マウントしたいテーマを追加
    ports: 
      - "5000:80"
    restart: always
    env_file: .env

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
      - 5001:80
    restart: always
    env_file: .env

volumes:
  db_volume:
